type: profile
dashboard:
  states:
    - component: main
      capability: universevoice35900.harmonyCommand
      version: 1
      idx: 0
      group: main
      values: []
  actions:
    - component: main
      capability: universevoice35900.harmonyCommand
      version: 1
      idx: 0
      group: main
detailView:
  - component: main
    capability: universevoice35900.harmonyCommand
    version: 1
    values: []
    patch: []
  - component: main
    capability: refresh
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: main
      capability: universevoice35900.harmonyCommand
      version: 1
      values: []
      patch: []
      exclusion: []
  actions:
    - component: main
      capability: universevoice35900.harmonyCommand
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: refresh
      version: 1
      values: []
      patch: []
      exclusion: []